/** @type {import("stylelint").Config} */
export default {
  extends: ["stylelint-config-standard-scss"],
  rules: {
    "unit-no-unknown": null,
    "custom-property-pattern": null,
    "color-hex-length": null,
    "scss/load-partial-extension": null,
    "selector-class-pattern": null,
    "at-rule-no-deprecated": true,
    "media-type-no-deprecated": true,
    "no-descending-specificity": null,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "font-family-no-duplicate-names": true,
    "keyframe-block-no-duplicate-selectors": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "block-no-empty": true,
    "comment-no-empty": true,
    "no-empty-source": true,
    "color-no-invalid-hex": true,
    "function-calc-no-unspaced-operator": true,
    "keyframe-declaration-no-important": true,
    "no-invalid-position-declaration": true,
    "string-no-newline": true,
    "syntax-string-no-invalid": true,
    "custom-property-no-missing-var-function": true,
    "selector-pseudo-class-no-unknown": true,
  },
};
